#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017


#spring.data.mongodb.uri=mongodb+srv://hd612002_db_user:LWvknxIBIHWZMuHp@cluster0.kb3jdrc.mongodb.net/?appName=Cluster0
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
#
#logging.level.org.springframework.security = DEBUG

#server.port:9091
#server.servlet.context-path: /users
